version: '3'

networks:
    mynetwork:
        name: mynetwork
        external: true

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

        ports:
            - 27017:27017
        networks:
            - mynetwork

    node_pagamento:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: node_pagamento
        ports:
            - '3000:3000'
        depends_on:
            - mongo
        networks:
            - mynetwork
